services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: Ðž1azSd*
      POSTGRES_DB: modul_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"