from django.db import models


class Cabinet(models.Model):
    city = models.TextField(null=False)
    shkaf_id = models.TextField(null=False)
    zone = models.TextField()
    location = models.TextField()
    street = models.TextField()
    extra_inf = models.TextField()


class Cell(models.Model):
    endpointid = models.IntegerField(verbose_name='EndpointID')
    cabinet = models.ForeignKey('Cabinet', related_name='cells', on_delete=models.CASCADE)
    stationid = models.IntegerField(verbose_name='StationID')
    balance_status = models.CharField(max_length=255, null=True, verbose_name='BALANCE_STATUS')
    capacity = models.CharField(max_length=255, null=True, verbose_name='CAPACITY')
    cap_coulo = models.CharField(max_length=255, null=True, verbose_name='CAP_COULO')
    cap_percent = models.CharField(max_length=255, null=True, verbose_name='CAP_PERCENT')
    cap_vol = models.CharField(max_length=255, null=True, verbose_name='CAP_VOL')
    charge_cap_h = models.CharField(max_length=255, null=True, verbose_name='CHARGE_CAP_H')
    charge_cap_l = models.CharField(max_length=255, null=True, verbose_name='CHARGE_CAP_L')
    charge_times = models.CharField(max_length=255, null=True, verbose_name='CHARGE_TIMES')
    core_volt = models.CharField(max_length=255, null=True, verbose_name='CORE_VOLT')
    current_cur = models.CharField(max_length=255, null=True, verbose_name='CURRENT_CUR')
    cycle_times = models.CharField(max_length=255, null=True, verbose_name='CYCLE_TIMES')
    design_voltage = models.CharField(max_length=255, null=True, verbose_name='DESIGN_VOLTAGE')
    fun_boolean = models.CharField(max_length=255, null=True, verbose_name='FUN_BOOLEAN')
    healthy = models.CharField(max_length=255, null=True, verbose_name='HEALTHY')
    ochg_state = models.CharField(max_length=255, null=True, verbose_name='OCHG_STATE')
    odis_state = models.CharField(max_length=255, null=True, verbose_name='ODIS_STATE')
    over_discharge_times = models.CharField(max_length=255, null=True, verbose_name='OVER_DISCHARGE_TIMES')
    pcb_ver = models.CharField(max_length=255, null=True, verbose_name='PCB_VER')
    remaining_cap = models.CharField(max_length=255, null=True, verbose_name='REMAINING_CAP')
    remaining_cap_percent = models.CharField(max_length=255, null=True, verbose_name='REMAINING_CAP_PERCENT')
    sn = models.CharField(max_length=255, null=True, verbose_name='SN')
    sw_ver = models.CharField(max_length=255, null=True, verbose_name='SW_VER')
    temp_cur1 = models.CharField(max_length=255, null=True, verbose_name='TEMP_CUR1')
    temp_cur2 = models.CharField(max_length=255, null=True, verbose_name='TEMP_CUR2')
    total_capacity = models.CharField(max_length=255, null=True, verbose_name='TOTAL_CAPACITY')
    vid = models.CharField(max_length=255, null=True, verbose_name='VID')
    voltage_cur = models.CharField(max_length=255, null=True, verbose_name='VOLTAGE_CUR')
    session_start = models.CharField(max_length=255, null=True, verbose_name='SESSION_START')
    session_end = models.CharField(max_length=255, null=True, verbose_name='SESSION_END')
    status = models.CharField(max_length=255, null=True, verbose_name='STATUS')
    time = models.CharField(max_length=255, null=True, verbose_name='time')


class Report(models.Model):
    endpointid = models.IntegerField(null=True)
    stationid = models.IntegerField(null=True)
    balance_status = models.CharField(max_length=255, null=True)
    capacity = models.CharField(max_length=255, null=True)
    cap_coulo = models.CharField(max_length=255, null=True)
    cap_percent = models.CharField(max_length=255, null=True)
    cap_vol = models.CharField(max_length=255, null=True)
    charge_cap_h = models.CharField(max_length=255, null=True)
    charge_cap_l = models.CharField(max_length=255, null=True)
    charge_times = models.CharField(max_length=255, null=True)
    core_volt = models.CharField(max_length=255, null=True)
    current_cur = models.CharField(max_length=255, null=True)
    cycle_times = models.CharField(max_length=255, null=True)
    design_voltage = models.CharField(max_length=255, null=True)
    fun_boolean = models.CharField(max_length=255, null=True)
    healthy = models.CharField(max_length=255, null=True)
    ochg_state = models.CharField(max_length=255, null=True)
    odis_state = models.CharField(max_length=255, null=True)
    over_discharge_times = models.CharField(max_length=255, null=True)
    pcb_ver = models.CharField(max_length=255, null=True)
    remaining_cap = models.CharField(max_length=255, null=True)
    remaining_cap_percent = models.CharField(max_length=255, null=True)
    sn = models.CharField(max_length=255, null=True)
    sw_ver = models.CharField(max_length=255, null=True)
    temp_cur1 = models.CharField(max_length=255, null=True)
    temp_cur2 = models.CharField(max_length=255, null=True)
    total_capacity = models.CharField(max_length=255, null=True)
    vid = models.CharField(max_length=255, null=True)
    voltage_cur = models.CharField(max_length=255, null=True)
    session_start = models.CharField(max_length=255, null=True)
    time = models.CharField(max_length=255, null=True)
    reason = models.CharField(max_length=255, null=True)
