# Generated by Django 5.0.4 on 2024-04-18 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('readable_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpointid', models.IntegerField(null=True)),
                ('stationid', models.IntegerField(null=True)),
                ('balance_status', models.CharField(max_length=255, null=True)),
                ('capacity', models.CharField(max_length=255, null=True)),
                ('cap_coulo', models.CharField(max_length=255, null=True)),
                ('cap_percent', models.CharField(max_length=255, null=True)),
                ('cap_vol', models.CharField(max_length=255, null=True)),
                ('charge_cap_h', models.CharField(max_length=255, null=True)),
                ('charge_cap_l', models.CharField(max_length=255, null=True)),
                ('charge_times', models.CharField(max_length=255, null=True)),
                ('core_volt', models.CharField(max_length=255, null=True)),
                ('current_cur', models.CharField(max_length=255, null=True)),
                ('cycle_times', models.CharField(max_length=255, null=True)),
                ('design_voltage', models.CharField(max_length=255, null=True)),
                ('fun_boolean', models.CharField(max_length=255, null=True)),
                ('healthy', models.CharField(max_length=255, null=True)),
                ('ochg_state', models.CharField(max_length=255, null=True)),
                ('odis_state', models.CharField(max_length=255, null=True)),
                ('over_discharge_times', models.CharField(max_length=255, null=True)),
                ('pcb_ver', models.CharField(max_length=255, null=True)),
                ('remaining_cap', models.CharField(max_length=255, null=True)),
                ('remaining_cap_percent', models.CharField(max_length=255, null=True)),
                ('sn', models.CharField(max_length=255, null=True)),
                ('sw_ver', models.CharField(max_length=255, null=True)),
                ('temp_cur1', models.CharField(max_length=255, null=True)),
                ('temp_cur2', models.CharField(max_length=255, null=True)),
                ('total_capacity', models.CharField(max_length=255, null=True)),
                ('vid', models.CharField(max_length=255, null=True)),
                ('voltage_cur', models.CharField(max_length=255, null=True)),
                ('session_start', models.CharField(max_length=255, null=True)),
                ('time', models.CharField(max_length=255, null=True)),
                ('reason', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('endpointid', models.IntegerField(primary_key=True, serialize=False)),
                ('stationid', models.IntegerField(null=True)),
                ('balance_status', models.CharField(max_length=255, null=True)),
                ('capacity', models.CharField(max_length=255, null=True)),
                ('cap_coulo', models.CharField(max_length=255, null=True)),
                ('cap_percent', models.CharField(max_length=255, null=True)),
                ('cap_vol', models.CharField(max_length=255, null=True)),
                ('charge_cap_h', models.CharField(max_length=255, null=True)),
                ('charge_cap_l', models.CharField(max_length=255, null=True)),
                ('charge_times', models.CharField(max_length=255, null=True)),
                ('core_volt', models.CharField(max_length=255, null=True)),
                ('current_cur', models.CharField(max_length=255, null=True)),
                ('cycle_times', models.CharField(max_length=255, null=True)),
                ('design_voltage', models.CharField(max_length=255, null=True)),
                ('fun_boolean', models.CharField(max_length=255, null=True)),
                ('healthy', models.CharField(max_length=255, null=True)),
                ('ochg_state', models.CharField(max_length=255, null=True)),
                ('odis_state', models.CharField(max_length=255, null=True)),
                ('over_discharge_times', models.CharField(max_length=255, null=True)),
                ('pcb_ver', models.CharField(max_length=255, null=True)),
                ('remaining_cap', models.CharField(max_length=255, null=True)),
                ('remaining_cap_percent', models.CharField(max_length=255, null=True)),
                ('sn', models.CharField(max_length=255, null=True)),
                ('sw_ver', models.CharField(max_length=255, null=True)),
                ('temp_cur1', models.CharField(max_length=255, null=True)),
                ('temp_cur2', models.CharField(max_length=255, null=True)),
                ('total_capacity', models.CharField(max_length=255, null=True)),
                ('vid', models.CharField(max_length=255, null=True)),
                ('voltage_cur', models.CharField(max_length=255, null=True)),
                ('session_start', models.CharField(max_length=255, null=True)),
                ('time', models.CharField(max_length=255, null=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_main.cabinet')),
            ],
        ),
        migrations.AddField(
            model_name='cabinet',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_main.city'),
        ),
    ]
