# Generated by Django 5.0.4 on 2024-04-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField()),
                ('shkaf_id', models.IntegerField()),
                ('zone', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('street', models.CharField(max_length=255)),
                ('extra_inf', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpointid', models.IntegerField(null=True)),
                ('stationid', models.IntegerField(null=True)),
                ('balance_status', models.CharField(max_length=255, null=True)),
                ('capacity', models.CharField(max_length=255, null=True)),
                ('cap_coulo', models.CharField(max_length=255, null=True)),
                ('cap_percent', models.CharField(max_length=255, null=True)),
                ('cap_vol', models.CharField(max_length=255, null=True)),
                ('charge_cap_h', models.CharField(max_length=255, null=True)),
                ('charge_cap_l', models.CharField(max_length=255, null=True)),
                ('charge_times', models.CharField(max_length=255, null=True)),
                ('core_volt', models.CharField(max_length=255, null=True)),
                ('current_cur', models.CharField(max_length=255, null=True)),
                ('cycle_times', models.CharField(max_length=255, null=True)),
                ('design_voltage', models.CharField(max_length=255, null=True)),
                ('fun_boolean', models.CharField(max_length=255, null=True)),
                ('healthy', models.CharField(max_length=255, null=True)),
                ('ochg_state', models.CharField(max_length=255, null=True)),
                ('odis_state', models.CharField(max_length=255, null=True)),
                ('over_discharge_times', models.CharField(max_length=255, null=True)),
                ('pcb_ver', models.CharField(max_length=255, null=True)),
                ('remaining_cap', models.CharField(max_length=255, null=True)),
                ('remaining_cap_percent', models.CharField(max_length=255, null=True)),
                ('sn', models.CharField(max_length=255, null=True)),
                ('sw_ver', models.CharField(max_length=255, null=True)),
                ('temp_cur1', models.CharField(max_length=255, null=True)),
                ('temp_cur2', models.CharField(max_length=255, null=True)),
                ('total_capacity', models.CharField(max_length=255, null=True)),
                ('vid', models.CharField(max_length=255, null=True)),
                ('voltage_cur', models.CharField(max_length=255, null=True)),
                ('session_start', models.DateTimeField(null=True, verbose_name='SESSION_START')),
                ('time', models.DateTimeField(null=True, verbose_name='time')),
                ('reason', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpointid', models.IntegerField(verbose_name='EndpointID')),
                ('balance_status', models.CharField(max_length=255, null=True, verbose_name='BALANCE_STATUS')),
                ('capacity', models.CharField(max_length=255, null=True, verbose_name='CAPACITY')),
                ('cap_coulo', models.CharField(max_length=255, null=True, verbose_name='CAP_COULO')),
                ('cap_percent', models.CharField(max_length=255, null=True, verbose_name='CAP_PERCENT')),
                ('cap_vol', models.CharField(max_length=255, null=True, verbose_name='CAP_VOL')),
                ('charge_cap_h', models.CharField(max_length=255, null=True, verbose_name='CHARGE_CAP_H')),
                ('charge_cap_l', models.CharField(max_length=255, null=True, verbose_name='CHARGE_CAP_L')),
                ('charge_times', models.CharField(max_length=255, null=True, verbose_name='CHARGE_TIMES')),
                ('core_volt', models.CharField(max_length=255, null=True, verbose_name='CORE_VOLT')),
                ('current_cur', models.CharField(max_length=255, null=True, verbose_name='CURRENT_CUR')),
                ('cycle_times', models.CharField(max_length=255, null=True, verbose_name='CYCLE_TIMES')),
                ('design_voltage', models.CharField(max_length=255, null=True, verbose_name='DESIGN_VOLTAGE')),
                ('fun_boolean', models.CharField(max_length=255, null=True, verbose_name='FUN_BOOLEAN')),
                ('healthy', models.CharField(max_length=255, null=True, verbose_name='HEALTHY')),
                ('ochg_state', models.CharField(max_length=255, null=True, verbose_name='OCHG_STATE')),
                ('odis_state', models.CharField(max_length=255, null=True, verbose_name='ODIS_STATE')),
                ('over_discharge_times', models.CharField(max_length=255, null=True, verbose_name='OVER_DISCHARGE_TIMES')),
                ('pcb_ver', models.CharField(max_length=255, null=True, verbose_name='PCB_VER')),
                ('remaining_cap', models.CharField(max_length=255, null=True, verbose_name='REMAINING_CAP')),
                ('remaining_cap_percent', models.CharField(max_length=255, null=True, verbose_name='REMAINING_CAP_PERCENT')),
                ('sn', models.CharField(max_length=255, null=True, verbose_name='SN')),
                ('sw_ver', models.CharField(max_length=255, null=True, verbose_name='SW_VER')),
                ('temp_cur1', models.CharField(max_length=255, null=True, verbose_name='TEMP_CUR1')),
                ('temp_cur2', models.CharField(max_length=255, null=True, verbose_name='TEMP_CUR2')),
                ('total_capacity', models.CharField(max_length=255, null=True, verbose_name='TOTAL_CAPACITY')),
                ('vid', models.CharField(max_length=255, null=True, verbose_name='VID')),
                ('voltage_cur', models.CharField(max_length=255, null=True, verbose_name='VOLTAGE_CUR')),
                ('session_start', models.DateTimeField(null=True, verbose_name='SESSION_START')),
                ('session_end', models.DateTimeField(null=True, verbose_name='SESSION_END')),
                ('status', models.CharField(max_length=255, null=True, verbose_name='STATUS')),
                ('time', models.DateTimeField(null=True, verbose_name='time')),
                ('cabinet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_main.cabinet')),
            ],
        ),
    ]
