# Generated by Django 5.0.4 on 2024-06-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('courier', 'Courier'), ('logistician', 'Logistician'), ('regional_manager', 'Regional Manager'), ('engineer', 'Engineer')], default='courier', max_length=20),
        ),
    ]
