# Generated by Django 5.0.4 on 2025-01-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet_history',
            name='first_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='cabinet_history',
            name='second_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='cabinet_history',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
