# Generated by Django 5.0.4 on 2024-04-30 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='shkaf_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='cabinet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_main.cabinet', to_field='shkaf_id'),
        ),
    ]
