# Generated by Django 5.0.4 on 2024-12-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='start_percent',
            field=models.CharField(max_length=255, null=True, verbose_name='START_PERCENT'),
        ),
        migrations.AddField(
            model_name='report',
            name='start_percent',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
