# Generated by Django 5.0.4 on 2024-05-30 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_main.city', to_field='city_name'),
        ),
    ]
