# Generated by Django 5.0.4 on 2024-04-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='session_end',
            field=models.CharField(max_length=255, null=True, verbose_name='SESSION_END'),
        ),
        migrations.AddField(
            model_name='cell',
            name='status',
            field=models.CharField(max_length=255, null=True, verbose_name='STATUS'),
        ),
    ]
