# Generated by Django 5.0.4 on 2025-01-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0002_cabinet_history_first_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet_history',
            name='first_half',
            field=models.IntegerField(default='0', verbose_name='FIRST_HALF'),
        ),
        migrations.AlterField(
            model_name='cabinet_history',
            name='second_half',
            field=models.IntegerField(default='0', verbose_name='SECOND_HALF'),
        ),
    ]
