# Generated by Django 5.0.4 on 2024-05-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0002_alter_cabinet_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
