# Generated by Django 5.0.4 on 2024-05-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0002_alter_cabinet_shkaf_id_alter_cell_cabinet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='vir_sn_eid',
            field=models.CharField(max_length=255, null=True, verbose_name='VIR_SN_EID'),
        ),
    ]
