# Generated by Django 5.0.4 on 2024-12-25 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0002_cell_start_percent_report_start_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_for', models.CharField(max_length=255, null=True, unique=True, verbose_name='HISTORY_FOR')),
                ('battery_count', models.IntegerField(null=True)),
                ('time', models.DateTimeField(null=True, verbose_name='time')),
                ('history_for_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_main.cabinet', to_field='shkaf_id')),
            ],
        ),
    ]
