# Generated by Django 5.0.4 on 2025-01-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0003_alter_cabinet_history_first_half_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet_history',
            name='first_data',
        ),
        migrations.RemoveField(
            model_name='cabinet_history',
            name='second_data',
        ),
    ]
