# Generated by Django 5.0.4 on 2024-05-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0003_alter_city_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='street',
            field=models.TextField(),
        ),
    ]
