# Generated by Django 5.0.4 on 2024-12-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0003_cabinet_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet_history',
            name='history_for',
            field=models.CharField(max_length=255, null=True, verbose_name='HISTORY_FOR'),
        ),
    ]
