# Generated by Django 5.0.4 on 2024-05-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0003_cell_vir_sn_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='vir_sn_eid',
            field=models.TextField(max_length=255, null=True, verbose_name='VIR_SN_EID'),
        ),
    ]
