# Generated by Django 5.0.4 on 2025-01-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0004_remove_cabinet_history_first_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='sw_name',
            field=models.CharField(max_length=255, null=True, verbose_name='SW_NAME'),
        ),
        migrations.DeleteModel(
            name='Cabinet_history',
        ),
    ]
