# Generated by Django 5.0.4 on 2024-07-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0004_alter_city_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='users',
        ),
    ]
