# Generated by Django 5.0.4 on 2025-01-20 09:47

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0005_cell_sw_name_delete_cabinet_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_half', models.IntegerField(default='0', verbose_name='FIRST_HALF')),
                ('second_half', models.IntegerField(default='0', verbose_name='SECOND_HALF')),
                ('first_data', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), size=None), size=None)),
                ('second_data', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), size=None), size=None)),
                ('date', models.DateTimeField(null=True)),
                ('history_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_main.cabinet', to_field='shkaf_id')),
            ],
        ),
    ]
