# Generated by Django 5.0.4 on 2024-07-03 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0006_customuser_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cities',
        ),
    ]
