# Generated by Django 5.0.4 on 2024-05-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0006_userroles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
