# Generated by Django 5.0.4 on 2025-01-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0006_cabinet_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cabinet_history',
        ),
    ]
