# Generated by Django 5.0.4 on 2024-07-03 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0007_remove_customuser_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='users',
            field=models.ManyToManyField(related_name='citys', to=settings.AUTH_USER_MODEL),
        ),
    ]
