# Generated by Django 5.0.4 on 2024-05-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0007_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
