# Generated by Django 5.0.4 on 2025-01-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0008_cabinet_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet_history',
            name='first_data',
        ),
        migrations.RemoveField(
            model_name='cabinet_history',
            name='second_data',
        ),
    ]
