# Generated by Django 5.0.4 on 2025-01-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0009_remove_cabinet_history_first_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet_history',
            name='test',
        ),
        migrations.AddField(
            model_name='cabinet_history',
            name='first_data',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='cabinet_history',
            name='second_data',
            field=models.BinaryField(null=True),
        ),
    ]
