# Generated by Django 5.0.4 on 2024-08-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0009_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
