# Generated by Django 5.0.4 on 2024-05-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ss_main', '0009_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='shkaf_id',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permission_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
