# Generated by Django 5.0.4 on 2024-09-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0009_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='is_error',
            field=models.BooleanField(default=False, verbose_name='IS_ERROR'),
        ),
    ]
