# Generated by Django 5.0.4 on 2025-01-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0010_remove_cabinet_history_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet_history',
            name='first_half',
            field=models.IntegerField(default='0', null=True, verbose_name='FIRST_HALF'),
        ),
        migrations.AlterField(
            model_name='cabinet_history',
            name='second_half',
            field=models.IntegerField(default='0', null=True, verbose_name='SECOND_HALF'),
        ),
    ]
