# Generated by Django 5.0.4 on 2024-05-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0010_alter_cabinet_shkaf_id_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='endpointid',
        ),
        migrations.AlterField(
            model_name='report',
            name='stationid',
            field=models.CharField(null=True),
        ),
    ]
