# Generated by Django 5.0.4 on 2025-01-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0011_alter_cabinet_history_first_half_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet_history',
            name='first_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cabinet_history',
            name='second_data',
            field=models.TextField(null=True),
        ),
    ]
