# Generated by Django 5.0.4 on 2024-05-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0011_remove_report_endpointid_alter_report_stationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
