# Generated by Django 5.0.4 on 2024-05-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0012_report_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='zone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
