# Generated by Django 5.0.4 on 2024-09-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0012_cell_last_sn_is_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=255, null=True, verbose_name='SN')),
            ],
        ),
    ]
