# Generated by Django 5.0.4 on 2025-02-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0012_alter_cabinet_history_first_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
