# Generated by Django 5.0.4 on 2024-09-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0013_marked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=255, null=True, verbose_name='SN')),
                ('session_start', models.DateTimeField(null=True, verbose_name='SESSION_START')),
                ('session_end', models.DateTimeField(null=True, verbose_name='SESSION_END')),
            ],
        ),
    ]
