# Generated by Django 5.0.4 on 2025-03-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0013_cabinet_latitude_cabinet_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet_settings_for_auto_marking',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cabinet_settings_for_auto_marking',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
