# Generated by Django 5.0.4 on 2024-09-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0014_battery_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Battery_history',
            new_name='All_batery_list',
        ),
    ]
