# Generated by Django 5.1.8 on 2025-06-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0015_remove_cabinet_settings_for_auto_marking_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='device_id',
            field=models.TextField(null=True),
        ),
    ]
