# Generated by Django 5.0.4 on 2024-09-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0015_rename_battery_history_all_batery_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='big_battary_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=255, null=True, verbose_name='SN')),
                ('year', models.CharField(max_length=255, null=True, verbose_name='YEAR')),
                ('cycle_times', models.CharField(max_length=255, null=True, verbose_name='CYCLE_TIMES')),
                ('is_tired', models.BooleanField(default=False, verbose_name='IS_TIRED')),
            ],
        ),
        migrations.DeleteModel(
            name='All_batery_list',
        ),
    ]
