# Generated by Django 5.1.8 on 2025-06-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0016_cabinet_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet_settings_for_auto_marking',
            name='temp_inside',
            field=models.CharField(null=True),
        ),
    ]
