# Generated by Django 5.0.4 on 2024-09-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0016_big_battary_list_delete_all_batery_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='last_sn',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='last_sn_is_error',
        ),
    ]
