# Generated by Django 5.1.8 on 2025-06-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0017_alter_cabinet_settings_for_auto_marking_temp_inside'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='buffer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='capacity',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='fire_allert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='rssi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='sense',
            field=models.TextField(null=True),
        ),
    ]
