# Generated by Django 5.1.8 on 2025-06-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0018_cabinet_buffer_cabinet_capacity_cabinet_fire_allert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='door_state',
            field=models.BooleanField(default=False),
        ),
    ]
