# Generated by Django 5.1.8 on 2025-06-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0019_cabinet_door_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet_settings_for_auto_marking',
            name='smoke_status',
            field=models.BooleanField(default=False, verbose_name='SMOKE_STATUS'),
        ),
    ]
