# Generated by Django 5.0.4 on 2024-10-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0019_cabinet_settings_for_auto_marking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet_settings_for_auto_marking',
            name='critical_temp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cabinet_settings_for_auto_marking',
            name='max_cycle_times',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cabinet_settings_for_auto_marking',
            name='temp_inside',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cabinet_settings_for_auto_marking',
            name='year_of_manufacture',
            field=models.IntegerField(null=True),
        ),
    ]
