# Generated by Django 5.0.4 on 2024-10-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0020_alter_cabinet_settings_for_auto_marking_critical_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet_settings_for_auto_marking',
            name='year_of_manufacture',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
