# Generated by Django 5.1.8 on 2025-06-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0020_cabinet_settings_for_auto_marking_smoke_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='sticker',
            field=models.TextField(null=True),
        ),
    ]
