# Generated by Django 5.0.4 on 2024-10-23 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0021_alter_cabinet_settings_for_auto_marking_year_of_manufacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet_settings_for_auto_marking',
            name='settings_for',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='SETTINGS_FOR'),
        ),
        migrations.CreateModel(
            name='Settings_for_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_error', models.BooleanField(default=False, verbose_name='SN_ERROR')),
                ('year_of_manufacture', models.BooleanField(default=False, verbose_name='YEAR_OF_MANUFACTURE')),
                ('max_cycle_times', models.BooleanField(default=False, verbose_name='MAX_CYCLE_TIMES')),
                ('vid', models.BooleanField(default=False, verbose_name='VID')),
                ('sw_ver', models.BooleanField(default=False, verbose_name='SW_VER')),
                ('settings_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_main.cabinet_settings_for_auto_marking', to_field='settings_for')),
            ],
        ),
    ]
