# Generated by Django 5.1.8 on 2025-08-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0022_cabinet_device_vendor_cabinet_energy_counter_sn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='grid_voltage',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='power_count',
            field=models.TextField(null=True),
        ),
    ]
