# Generated by Django 5.0.4 on 2024-10-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0022_cabinet_settings_for_auto_marking_settings_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet_settings_for_auto_marking',
            name='max_cycle_times',
            field=models.CharField(null=True),
        ),
    ]
