# Generated by Django 5.1.8 on 2025-08-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0023_cabinet_grid_voltage_cabinet_power_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='temperature1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='temperature2',
            field=models.TextField(null=True),
        ),
    ]
