# Generated by Django 5.1.8 on 2025-09-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_main', '0024_cabinet_temperature1_cabinet_temperature2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventlogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('shkaf_id', models.CharField(max_length=255)),
                ('readable_name', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('time', models.DateTimeField(null=True, verbose_name='time')),
                ('door_state_before', models.BooleanField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cabinet',
            name='readable_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='abbreviation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
